/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2020 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

/*
Write a program to execute an SVC instruction from thread mode,
implement the svc handler to print the SVC number used.
Also,  increment the SVC number by 4 and return it to the thread mode code and print it.
Hints :
1)Write a main() function where you should execute the SVC instruction with an argument.
let's say SVC #0x5
2)Implement the SVC handler
3)In the SVC handler extract the SVC number and print it using printf
4) Increment the SVC number by 4 and return it to the thread mode
*/

#include <stdio.h>
#include <stdint.h>

int main(void)
{
	__asm ("SVC #12");

	//register uint32_t data __asm ("r0");

	uint32_t data;

	__asm volatile ("MOV %0,R0": "=r"(data):  );

	printf("data = %ld\n",data);
    /* Loop forever */
	for(;;);
}

__attribute__((naked)) void SVC_Handler (void){

	//1.get the value of MSP
	__asm ("MRS R0,MSP");
	__asm ("B SVC_Handler_c");


}

void SVC_Handler_c(uint32_t* pBaseOfStackFrame){

	printf("In SVC Handler\n");

	uint8_t *pReturn_addr = (uint8_t*) pBaseOfStackFrame[6];

	//2.decreament the address by 2 to point to
	//opcode of SVC instruction in program memory

	pReturn_addr-=2;

	//3. Get the SVC number

	uint8_t SVC_number = *pReturn_addr;

	printf("SVC number is %d\n",SVC_number);

	SVC_number+=4;

	pBaseOfStackFrame[0]=SVC_number;

}
