/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2020 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include <stdio.h>
#include <stdint.h>

int main(void)
{
    /* Loop forever */

	//1. Enable all configurable exceptions Usage_Fault, mem manage fault and bus fault

	uint32_t *pSHCSR = (uint32_t*) 0xE000ED24;

	*pSHCSR |= (1 << 16); //mem_manage fault
	*pSHCSR |= (1 << 17); //bus fault
	*pSHCSR |= (1 << 18); //usage fault

	//3.Let's force the processor to execute undefined instructions

	uint32_t *pSRAM= (uint32_t*)0x20010000;
	*pSRAM= 0xFFFFFFFF;

	void (*some_address)(void);

	 some_address = (void*)pSRAM;
	//some_address = (void*)((uint32_t)pSRAM+1);

	some_address();


	//4. Analyze the fault
	for(;;);
}

//2. Implement Fault Handlers

void HardFault_Handler(void){

	printf("In HardFault Exception Handler ");
	while(1);

}

void MemManage_Handler(void){

	printf("In MemManage Exception Handler\n ");
	while(1);

}

void BusFault_Handler(void){

	printf("In BusFault Exception Handler\n ");
	while(1);
}

__attribute__((naked)) void UsageFault_Handler (void){

	//here we extracted the value of MSP which happens to be the
	//base address of stack frame which got saved during exception entry
	//from thread mode to handler mode
	__asm ("MRS r0,MSP");
	__asm ("B UsageFault_Handler_c");


}

void UsageFault_Handler_c(uint32_t *pBaseStackFrame){




	uint32_t *pUFSR = (uint32_t*)0xE000ED2A;
	printf("In UsageFault Exception Handler\n ");
	printf("UFSR = %lx\n ", (*pUFSR) & 0xFFFF);
	printf("pBaseStackFrame = %p\n ", pBaseStackFrame);
	printf("value of R0 = %lx\n ", pBaseStackFrame[0]);
	printf("value of R1 = %lx\n ", pBaseStackFrame[1]);
	printf("value of R2 = %lx\n ", pBaseStackFrame[2]);
	printf("value of R3 = %lx\n ", pBaseStackFrame[3]);
	printf("value of R12 = %lx\n ", pBaseStackFrame[4]);
	printf("value of LR = %lx\n ", pBaseStackFrame[5]);
	printf("value of PC = %lx\n ", pBaseStackFrame[6]);
	printf("value of xPSR = %lx\n ", pBaseStackFrame[7]);

	while(1);

}
