/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2020 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#define IRQNO_TIMER2 28
#define IRQNO_I2C2 31

#include <stdio.h>
#include <stdint.h>

uint32_t *pNVIC_IPRBase = (uint32_t*)0xE000E400;
uint32_t *pNVIC_ISERBase = (uint32_t*)0xE000E100;
uint32_t *pNVIC_ISPRBase = (uint32_t*)0xE000E200;

void configure_priority_for_irqs(uint8_t irq_no,uint8_t priority_value){

	//1. Find out iprx

	uint8_t iprx = irq_no/4;

	uint32_t *ipr = pNVIC_IPRBase + iprx;

	//2. Find pos in iprx

	uint8_t pos = (irq_no%4)*8;

	//3. Configure the priority

	*ipr &= ~(0xFF << pos); //clear
	*ipr |= (priority_value << pos);

}

int main(void)
{
    /* Loop forever */

	//1. Configure the priority for the peripherals

	configure_priority_for_irqs(IRQNO_TIMER2,0x80);
	configure_priority_for_irqs(IRQNO_I2C2,0x70);


	//2. Set the interrupt pending bit in NVIC PR

	*pNVIC_ISPRBase |= (1 << IRQNO_TIMER2 );

	//3.Enable the IRQ's in NVIC ISER

	*pNVIC_ISERBase |= (1 << IRQNO_I2C2 );
	*pNVIC_ISERBase |= (1 << IRQNO_TIMER2 );


	for(;;);
}

void TIM2_IRQHandler(void){

    printf("IN TIMER2 IRQ HANDLER\N");

	*pNVIC_ISPRBase |= (1 << IRQNO_I2C2 );

	while(1);


}

void I2C1_EV_IRQHandler(void){

    printf("IN I2C1 IRQ HANDLER\N");


}
